package AnalizadorLexico;

public enum TipoToken {
    // Crear un tipoToken por palabra reservada
    // Crear un tipoToken: identificador, una cadena y numero
    // Crear un tipoToken por cada "Signo del lenguaje" (ver clase Scanner)


    // PALABRAS RESERVADAS:
    If, ELSE, WHILE, FOR, DO, SWITCH, CASE, DEFAULT,
    BREAK, CONTINUE, RETURN, TRY, CATCH, THROW, FINALLY,
    PUBLIC, PRIVATE, PROTECTED, CLASS, INTREFACE, ENUM, EXTENDS,
    IMPLEMENTS, PACKAGE, IMPORT, STATIC, FINAL, ABSTRACT, SYNCHRONIZED,
    VOLATILE, TRANSIENT, NATIVE, SUPER, THIS, INSTANCEOF, NEW, TRUE, FALSE, NULL,

    //IDENTIFICADORES: 
    
    IDENTIFICADOR,
    CADENA,
    NUMERO, 
    

    //SIGNOS DE LENGUAJE:
    PUNTO, PUNTO_Y_COMA, DOS_PUNTOS, COMA, SIGNO_DE_INTERROGACION,
    SIGNO_DE_EXCLAMACION, PARENTESIS_IZQ, PARENTESIS_DER, 
    CORCEHTE_IZQ, CORCHETE_DER, LLAVE_IZQ, LLAVE_DER, GUION_MEDIO, 
    GUION_BAJO, DIERESIS, DIAGONAL, DIAGONAL_INV, ASTERISCO, NUMERAL, 
    AMPERSAND, PORCENTAJE, MAYORQUE, MENORQUE, MAYOR_IGUAL, MENOR_IGUAL,
    IGUAL, SUMA, RESTA, MULTIPLICACION, COMILLAS_DOB, COMILLAS_SIM, PIPA,

    // Final de cadena
    EOF
}
